version: "3.9"

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: sampledb
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-overlay
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  api:
    image: sample-api:v2  # ensure image is built & pushed if multi-node
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app-overlay
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
      resources:
        limits:
          cpus: '0.5'
          memory: '512M'
        reservations:
          cpus: '0.25'
          memory: '256M'

volumes:
  db-data:

networks:
  app-overlay:
    external: true

